### ISSUE TITLE
Sync does not pull pvl files

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/vscode-ext#18]
Layouts files do not get synced with an instance. Should pvl files sync with local files? As a developer, I would expect these files to be downloaded.

<img width="957" alt="Screenshot 2023-01-17 at 3 46 20 PM" src="https://user-images.githubusercontent.com/9896546/213009058-fd52ba9a-162b-4655-a28f-cb78dc069dac.png">

**Comment by allenpigar** [comment]
Please install the new version of extension and retest this.

![vscode-pvl-issue](https://user-images.githubusercontent.com/50983144/213510708-a3443c48-a946-43fa-ac59-e70e7a1741c0.gif)
