### ISSUE TITLE
Add a message alert for expired token

### ISSUE THREAD

**Issue by gtllien** [zesty-io/vscode-ext#25]
**Usecase:**
User is having issues using VSCode plugin not syncing instances; tried deleting folder and reinitializing the project but same issue

The issue resolved when advised to renew its api/dev token.

**Expected behaviour:**
Add an error message/alert when the api/dev token is already expired so the user will know why the instance is not syncing, and will be able to resolve by renewing its token

**Comment by allenpigar** [comment]
Added expired token alert when making file changes in the instance.
![expired-token-alert](https://github.com/zesty-io/vscode-ext/assets/50983144/8612703f-cace-495f-82b9-cc290e23ca95)
