### ISSUE TITLE
Request to use a different folder other than /webengine to sync files to

### ISSUE THREAD

**Issue by gtllien** [zesty-io/vscode-ext#27]
**Describe the Feature**
Customer request to use a different folder than the `/webengine` folder to sync the files/folders into.

**Comment by allenpigar** [comment]
hi lien, can you give more context on this issue. Is there any specific use case why we need to have other folder to sync the files. currently /webengine folder is the default directory that the zesty.config.js is mapped to.

**Comment by allenpigar** [comment]
@gtllien any updates on this ticket?

**Comment by gtllien** [comment]
@allenpigar Apologies for the delayed response. I haven't heard any updates from the user who requested this. Feel free to close and will just create a new ticket once I heard back from them. Thanks
